### PR TITLE
added docker support

### PR DESCRIPTION
**Pull request by anupammaurya6767**
added docker support
@ParthJohri

### CODE REVIEW

**Review by ParthJohri — CHANGES_REQUESTED** [review]
Good work 🥂
@anupammaurya6767 Since you've added docker support could you please do the necessary changes on the readme as well to facilitate users to easily use this bot!

Regarding my contact info you can dm me on LinkedIn.

**Comment by anupammaurya6767** [comment]
@ParthJohri done, now check

**Comment by ParthJohri** [comment]
Great work @anupammaurya6767 and good going 💪
PS : Also next time try not to commit gpt stuff :P

**Comment by anupammaurya6767** [comment]
> Great work @anupammaurya6767 and good going 💪
> PS : Also next time try not to commit gpt stuff :P

Used only for starting template, sir 😂

**Comment by ParthJohri** [comment]
> > Great work @anupammaurya6767 and good going 💪
> > PS : Also next time try not to commit gpt stuff :P
> 
> Used only for starting template, sir 😂

Haha been there 😂, anyways you have a good dev profile, keep it up buddy 🥂

**Pull request merged**
